services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    networks:
      - traefik-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`intranet.lanbeforetime.link`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls=true"

volumes:
  config:
    driver: local

networks:
  traefik-net:
    external: true