- name: Basic system configuration
  hosts: logserver
  become: yes
  roles:
    - role: debian-base
      vars:
        cloud_init: true
    - role: install-docker
      vars:
        use_docker_repo: true
    #- role: firewalld-base
    #  vars:
    #    firewall_open_services:
    #      - ssh
    #      - mdns
    #      - http
    #      - https
    #    firewall_open_ports:
    #      # This is for traefik dashboard
    #      - '41235/tcp'

# - name: Deploy traefik
#   hosts: logserver
#   roles: 
#     - role: deploy-docker-compose_v2
#       vars:
#         local_path: logserver/traefik
#         remote_path: /home/groot/traefik
#         env_variables:
#           CF_API_EMAIL: "{{ cloudflare_email }}"
#           CF_DNS_API_TOKEN: "{{ cloudflare_dns_api_token }}"

- name: Deploy graylog
  hosts: logserver
  roles: 
    - role: deploy-docker-compose_v2
      vars:
        local_path: logserver/graylog
        remote_path: /home/groot/graylog
        env_variables:
          GRAYLOG_PASSWORD_SECRET: "{{ logserver_graylog_password_secret }}"
          GRAYLOG_ROOT_PASSWORD_SHA2: "{{ logserver_graylog_root_password_hash }}"
