- name: Basic system configuration
  hosts: snmpserver
  become: yes
  roles:
    - role: debian-base
      vars:
        cloud_init: true
    - role: install-docker
      vars:
        use_docker_repo: true
    #- role: firewalld-base
    #  vars:
    #    firewall_open_services:
    #      - ssh
    #      - mdns
    #      - http
    #      - https
    #    firewall_open_ports:
    #      # This is for traefik dashboard
    #      - '41235/tcp'

# - name: Deploy traefik
#   hosts: snmpserver
#   roles: 
#     - role: deploy-docker-compose_v2
#       vars:
#         local_path: logserver/traefik
#         remote_path: /home/groot/traefik
#         env_variables:
#           CF_API_EMAIL: "{{ cloudflare_email }}"
#           CF_DNS_API_TOKEN: "{{ cloudflare_dns_api_token }}"


